### ISSUE TITLE
Cluster start issues: ModuleNotFoundError: No module named 'diagnose'

### ISSUE THREAD

**Issue by kvshams** [Nealelab/cloudtools#45]
Trying to install cloud tools and the installation seemed to be successful (Mac OS) . When I try to initiate cluster command I am getting following error

`cluster -h

Traceback (most recent call last):
  File "/Users/svellari/anaconda3/bin/cluster", line 11, in <module>
    load_entry_point('cloudtools==1.1.5', 'console_scripts', 'cluster')()
  File "/Users/svellari/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/svellari/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/Users/svellari/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/Users/svellari/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/svellari/anaconda3/lib/python3.6/site-packages/cloudtools/__main__.py", line 6, in <module>
    import diagnose
ModuleNotFoundError: No module named 'diagnose'
`
There is no module named 'diagnose' available in repository

**Comment by danking** [comment]
@kvshams we now regularly test against python2 and python3 and we test [`cluster start --help`](https://github.com/Nealelab/cloudtools/blob/master/hail-ci-build.sh#L39). Please re-open if this continues to be a problem with latest cloud tools!
